databases:
  name: postgres_db
  databaseName: koala
  user: visionect
  password: visionect
  postgresMajorVersion: 12
  port: 5432
  ipAllowList: []

services:
  - type: redis
    name: redis
    ipAllowList: []

  - type: web
    env: docker
