databases:
  - name: postgres_db
    databaseName: koala
    user: visionect
    postgresMajorVersion: 12
    ipAllowList: []

services:
  - type: redis
    name: redis
    ipAllowList: []

  - type: web
    name: vss
    env: docker
    disk:
      name: dev
      mountPath: /dev
