databases:
  - name: postgres_db
    databaseName: koala
    user: visionect
    postgresMajorVersion: 12
    ipAllowList: []

services:
  - type: redis
    name: redis
    ipAllowList: []

  - type: web
    env: docker
